---
- hosts: localhost
  tasks:
    - name: Print all the vpc information
      ansible.builtin.debug:
        msg: "{{ WF_VPC }}"

    - name: Print only the VPC_ID
      ansible.builtin.debug:
        msg: "{{ WF_VPC.vpc.id }}"

    - name: Print subnet information
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ AWS_REGION }}"
      register: ec2net

    - name: Print only the VPC_ID
      ansible.builtin.debug:
        msg: "{{ ec2net }}"
