---
- hosts: localhost
  tasks:
    - name: Creating workflow variables
      # Use the built in set_stats method to allow us to
      # persist variables throughout the workflow.
      #
      # Although many of these variables could be used in a
      # survey for each playbook. It makes it easier to
      # read when storing each parameter in a workflow
      # variable before passing through the playbooks.
      #
      # This is just my personal preference :)

      ansible.builtin.set_stats:
        data:
          WF_VPC_NAME: "vpc_{{ DEMO_NAME }}"
          WF_VPC_CIDR: "{{ VPC_CIDR }}"
          WF_VPC_PUBLIC_CIDR: "{{ VPC_PUBLIC_CIDR }}"
          WF_VPC_REGION: "{{ VPC_REGION }}"
          WF_VPC_DNS_HOSTNAMES: yes
          WF_VPC_DNS_SUPPORT: yes
          WF_VPC_SECURITY_GROUP: "{{ AWS_SECURITY_GROUP }}"
          WF_VPC_PUBLIC_SUBNET_NAME: "subnet_public_{{ DEMO_NAME }}"

        aggregate: no
