---
- name: "create the VPC {{ VPC_NAME }}"
  amazon.aws.ec2_vpc_net:
    name: "{{ VPC_NAME }}"
    cidr_block: "{{ VPC_CIDR }}"
    region: "{{ AWS_REGION }}"
    dns_hostnames: "{{ VPC_DNS_HOSTNAMES }}"
    dns_support: "{{ VPC_DNS_SUPPORT }}"
    tags:
      automated: "yes"
      workflow_tag: "{{ WF_AWS_TAG }}"

    tenancy: dedicated
  register: vpcdata

- name: Storing the VPC_ID
  ansible.builtin.set_stats:
    data:
      WF_VPC: "{{ vpcdata }}"
    aggregate: no
# - name: "Collect VPC information"
#   amazon.aws.ec2_vpc_net_info:
#     region: "{{ AWS_REGION }}"

# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts

# - name: Setting stats (not aggregating)
#   ansible.builtin.set_stats:
#     data:
#       the_answer: 42
#     aggregate: no
