---
- name: "create the subnet {{ WF_VPC_NAME }}"
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ WF_VPC_ID }}"
    cidr: "{{ WF_VPC_PUBLIC_CIDR }}"
    region: "{{ AWS_REGION }}"
    map_public: yes
    tags:
      Name: "{{ WF_VPC_PUBLIC_SUBNET_NAME }}"
  register: database_subnet

- name: Storing the VPC_ID
  ansible.builtin.set_stats:
    data:
      WF_PUBLIC_SUBNET_ID: "{{ database_subnet.subnet.id }}"
    aggregate: no
