---
- name: "create the subnet {{ VPC_NAME }}"
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpcdata.vpc.id }}"
    cidr: "{{ VPC_PUBLIC_SUBNET }}"
    region: "{{ AWS_REGION }}"
    map_public: yes
    tags:
      Name: "{{ VPC_PUBLIC_SUBNET_NAME }}"
  register: database_subnet

- name: Print subnet information
  amazon.aws.ec2_vpc_subnet_info:
    region: "{{ database_subnet }}"
