---
- name: "create the subnet {{ VPC_NAME }}"
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpcdata.vpc.id }}"
    cidr: "{{ VPC_PUBLIC_SUBNET }}"
    region: "{{ AWS_REGION }}"
    map_public: yes
    tags:
      Name: "{{ VPC_PUBLIC_SUBNET_NAME }}"
  register: database_subnet

- name: Storing the VPC_ID
  ansible.builtin.set_stats:
    data:
      WF_AWS_SUBNET: "{{ database_subnet }}"
    aggregate: no
