---
# Create the demo VPC, collect the VPC information
# and then store the VPC details.
- name: "create the VPC {{ WF_VPC_NAME }}"
  amazon.aws.ec2_vpc_net:
    name: "{{ WF_VPC_NAME }}"
    cidr_block: "{{ WF_VPC_CIDR }}"
    region: "{{ WF_VPC_REGION }}"
    dns_hostnames: "{{ WF_VPC_DNS_HOSTNAMES }}"
    dns_support: "{{ WF_VPC_DNS_SUPPORT }}"
    tags:
      automated: "yes"
      workflow_tag: "{{ WF_VPC_NAME }}"

    tenancy: dedicated
  register: vpcdata

- name: Storing the VPC_ID
  ansible.builtin.set_stats:
    data:
      WF_VPC_ID: "{{ vpcdata.vpc.id }}"
      WF_AWS_SECURITY_GROUP: "{{ AWS_SECURITY_GROUP }}"
    aggregate: no
