---
# Basic provisioning example
- name: Provision a RHEL VM
  amazon.aws.ec2:
    key_name: "{{ AWS_KEYPAIR }}"
    instance_type: "t2.micro"
    # The default RHEL 9 image
    image: ami-0e3c9f42c088b4728
    wait: yes
    group: "default"
    count: 1
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes

# tasks file for aws_infrastructure
- name: Provision a set of instances
  ec2:
    aws_access_key: "t2.micro{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    key_name: "{{ aws_keypair_name}}"
    group: "{{ aws_sect2.microurity_group }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_ami_id }}"
    wait: true
    region: "{{ aws_availability_zone }}"
    exact_count: "{{ aws_instance_count }}"
    count_tag:
      Name: Demo
    instance_tags:
      Name: Demo
  register: ec2

- debug:
    msg: "{{ ec2 }}"
