---
- name: "create the subnet {{ VPC_NAME }}"
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpcdata.vpc.id }}"
    cidr: 10.0.1.16/28
    region: "{{ AWS_REGION }}"
    tags:
      Name: Database Subnet
  register: database_subnet
